name: Android CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: upload to aws devicefarm
      uses: realm/aws-devicefarm/create-upload@v1
      id: create-upload
      with:
         project_arn: arn:aws:devicefarm:us-west-2:102525726332:project:0ea2422d-726a-40c1-8667-6a91d75e66a7
         name: app_debug.apk
         type: ANDROID_APP
         
    - name: get-upload
      uses: realm/aws-devicefarm/get-upload@v1
      id: get-upload
      with:
           ressource-arn: ${{steps.create-upload.outputs.arn}}
      
    - name: print status
      run: echo ${{steps.get-upload.outputs.status}}
      
  
