

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build assembleDebug
        
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
         arguments: test

#   deploy:
#     needs: [build]
#     runs-on: ubuntu-latest
   
#     steps:
#      - uses: actions/checkout@v3
         
#      - name: setup aws credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
#          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#          aws-region: ${{secrets.AWS_REGION}}
         
#      - name: Deploy
#        run: |
#           aws devicefarm create-upload --project-arn arn:aws:devicefarm:us-west-2:102525726332:project:0ea2422d-726a-40c1-8667-6a91d75e66a7 --name app/build/outputs/apk/debug/app-debug.apk --type ANDROID_APP
#           aws devicefarm schedule-run --project-arn arn:aws:devicefarm:us-west-2:102525726332:project:0ea2422d-726a-40c1-8667-6a91d75e66a7 --device-pool-arn ${{secrets.AWS_DEVICE_POOL_ARN}} --test type=BUILTIN_FUZZ
         
         
        
        
        
        
        
        
        
