name: my workflow

on: workflow_dispatch

jobs:

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - id: step1
        run: |
          Name="Deverly"
          echo "test=$Name" >> $GITHUB_OUTPUT
 
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job3:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{needs.job1.outputs.output1 == 'Deverly'}}    
    steps:
     -  uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Success')
