name: my workflow

on: workflow_dispatch

jobs:

  jobs1:
    runs-on: ubuntu-latest
    
    steps:
     - name: step 1
       run: |
         echo "Hello my name is Deverly Gousse" > name.txt
         
     - name: upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: name.txt
         path: ./name.txt
         
  jobs2:
     needs: jobs1
     runs-on: ubuntu-latest
     
     steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
         name: name.txt
         
      - run: |
          info=$(cat name.txt)
          echo $info
         
